#!/bin/bash

#enter into the Programs folder
cd /home/kevin/Programs

# ask for the langue
echo "Langue?"
read langue

#Enter in the folder corresponding with the langue
case $langue in
	"c++") cd Cplus ;;
	"js")  cd JavaScript ;;
	"bash") cd shell-tuto ;;
esac

#ask for the name of the Proyect to create it 
echo "Proyect?"
read proyect
mkdir $proyect
cd $proyect

#ask for the name of the file and create it
echo "Name File?"
read file
case $langue in
	"c++") filee="$file.cpp" ;;
	"js")  filee="$file.js" ;;
	"bash")  filee="$file.sh" ;;
	*) echo "no extension" ;;
esac	
touch $filee

#select special features for each langue in each proyect
if [ "$langue" == "c++" ]
	then
		echo "#!/bin/bash" > run
		echo "g++ $filee -o $file" >> run
		echo "echo -e '\E[01;33m'"  >> run
		echo "./$file" >> run
		echo "tput sgr0 #" >> run
		chmod +x run 
fi
# write a document .sublime_project
echo "{" > $proyect.sublime-project
echo "	\"folders\":" >> $proyect.sublime-project
echo "	[" >> $proyect.sublime-project
echo "		{" >> $proyect.sublime-project
echo "			\"follow_symlinks\": true," >> $proyect.sublime-project
echo "			\"path\": \".\"" >> $proyect.sublime-project
echo "		}" >> $proyect.sublime-project
echo "	]" >> $proyect.sublime-project
echo "}" >> $proyect.sublime-project

#write an alias
echo "alias $proyect='cd $(pwd)'" >> ~/.bashrc

#open sublime in the folder
subl3 $(pwd)